name: flutter_app_quiz_game
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  scrollable_positioned_list: ^0.3.4
  google_mobile_ads: ^2.0.0
  google_fonts:
  assets_audio_player: ^3.0.3+9
  url_launcher: ^6.0.17
  in_app_purchase: ^2.0.1
  in_app_purchase_storekit: ^0.2.0
  #  Check if new version is released
  #  charts_flutter: ^0.12.0
  charts_flutter_new: ^0.12.0
  numberpicker: ^2.1.1
  function_tree: ^0.8.12
  animated_background: ^2.0.0
  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  #UPDATE IF LIBS CHANGE!!
  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  #sudo gem install cocoapods
  #pod deintegrate; pod install; pod update;
  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/main/buttons/
    - assets/main/general/
    - assets/main/popup/
    - assets/main/audio/
    ########################
    ###### HANGMAN ###############################################################################
    ########################
    - assets/implementations/hangman/
    - assets/implementations/hangman/game/
    - assets/implementations/hangman/campaign/
    - assets/implementations/hangman/campaign/background/
    - assets/implementations/hangman/campaign/buttons/
    - assets/implementations/hangman/campaign/l_0/
    - assets/implementations/hangman/campaign/l_1/
    - assets/implementations/hangman/campaign/l_2/
    - assets/implementations/hangman/campaign/l_3/
    - assets/implementations/hangman/campaign/l_4/
    - assets/implementations/hangman/campaign/l_5/
    ########################
    ###### ASTRONOMY #############################################################################
    ########################
    #    - assets/implementations/astronomy/
    #    - assets/implementations/astronomy/audio/
    #    - assets/implementations/astronomy/buttons/
    #    - assets/implementations/astronomy/categories/
    #    - assets/implementations/astronomy/planets/
    #    - assets/implementations/astronomy/questions/cat11/
    #    - assets/implementations/astronomy/questions/cat12/
    #    - assets/implementations/astronomy/questions/cat13/
    #    - assets/implementations/astronomy/questions/cat15/
    #    - assets/implementations/astronomy/questions/cat16/
    ########################
    ###### IQGAME ################################################################################
    ########################
    #    - assets/implementations/iqgame/
    #    - assets/implementations/iqgame/buttons/
    #    - assets/implementations/iqgame/cat0/
    #    - assets/implementations/iqgame/cat1/
    #    - assets/implementations/iqgame/cat2/
    #    - assets/implementations/iqgame/cat5/
    ########################
    ###### ANATOMY #################################################################################
    ########################
    #    - assets/implementations/anatomy/
    #    - assets/implementations/anatomy/buttons/
    #    - assets/implementations/anatomy/general/
    #    - assets/implementations/anatomy/categories/
    #    - assets/implementations/anatomy/questions/diff4/cat0/
    #    - assets/implementations/anatomy/questions/diff4/cat1/
    #    - assets/implementations/anatomy/questions/diff4/cat2/
    #    - assets/implementations/anatomy/questions/diff4/cat3/
    #    - assets/implementations/anatomy/questions/diff4/cat4/
    #    - assets/implementations/anatomy/questions/diff4/cat5/
    #    - assets/implementations/anatomy/questions/diff4/cat6/
    #    - assets/implementations/anatomy/questions/diff4/cat7/
    #    - assets/implementations/anatomy/questions/diff4/cat8/
    #    - assets/implementations/anatomy/questions/diff4/cat9/
    #    - assets/implementations/anatomy/questions/diff4/cat10/
    #    - assets/implementations/anatomy/questions/diff4/cat11/
    ########################
    ###### DOPEWARS ################################################################################
    ########################
    #    - assets/implementations/dopewars/
    #    - assets/implementations/dopewars/buttons/
    #    - assets/implementations/dopewars/general/
    #    - assets/implementations/dopewars/resource_background/
    ########################
    ###### PERSTEST ################################################################################
    ########################
    #    - assets/implementations/perstest/
    #    - assets/implementations/perstest/buttons/
    ########################
    ###### GEOQUIZ #################################################################################
    ########################
    #    - assets/implementations/geoquiz/
    #    - assets/implementations/geoquiz/questions/images/cat7/
    #    - assets/implementations/geoquiz/questions/images/cat9/
    #    - assets/implementations/geoquiz/questions/images/diff0/cat5/
    #    - assets/implementations/geoquiz/questions/images/diff0/cat8/
    #    - assets/implementations/geoquiz/questions/images/diff1/cat5/
    #    - assets/implementations/geoquiz/questions/images/diff1/cat8/
    #    - assets/implementations/geoquiz/questions/images/diff2/cat5/
    #    - assets/implementations/geoquiz/questions/images/diff2/cat8/
    #    - assets/implementations/geoquiz/questions/images/diff3/cat5/
    #    - assets/implementations/geoquiz/questions/images/diff3/cat8/
    ########################
    ###### HISTORY #################################################################################
    ########################
#    - assets/implementations/history/
#    - assets/implementations/history/buttons/
#    - assets/implementations/history/questions/images/diff0/cat0/
#    - assets/implementations/history/questions/images/diff0/cat1/
#    - assets/implementations/history/questions/images/diff0/cat2/
#    - assets/implementations/history/questions/images/diff0/cat3/
#    - assets/implementations/history/questions/images/diff0/cat4/
#    - assets/implementations/history/questions/images/diff1/cat0/
#    - assets/implementations/history/questions/images/diff1/cat1/
#    - assets/implementations/history/questions/images/diff1/cat2/
#    - assets/implementations/history/questions/images/diff1/cat3/
#    - assets/implementations/history/questions/images/diff1/cat4/
#    - assets/implementations/history/questions/images/diff2/cat0/
#    - assets/implementations/history/questions/images/diff2/cat1/
#    - assets/implementations/history/questions/images/diff2/cat2/
#    - assets/implementations/history/questions/images/diff2/cat3/
#    - assets/implementations/history/questions/images/diff2/cat4/
#    - assets/implementations/history/questions/images/diff3/cat0/
#    - assets/implementations/history/questions/images/diff3/cat2/
#    - assets/implementations/history/questions/images/diff3/cat3/
